### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by brummski** [QuadStingray/docker-speedtest-influxdb#1]
Hello, i have a 1G line here, and get different speeds which is strange:
root@foo:/opt/docker-speedtest-influxdb# speedtest-cli --server 14704
Retrieving speedtest.net configuration...
Testing from Telecom Italia Business (85.44.190.68)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Telecom Italia S.p.A. (Reggio Calabria) [634.49 km]: 24.935 ms
Testing download speed................................................................................
Download: 433.86 Mbit/s
Testing upload speed................................................................................................
Upload: 435.34 Mbit/s

and on grafana for example Upload is always less then 100Mbit  - do you have an idea what i am doing wrong?

**Comment by QuadStingray** [comment]
Hello,

did you used the predefined grafana dashboard (https://github.com/QuadStingray/docker-speedtest-influxdb/blob/master/docker/grafana/provisioning/dashboards/speedtest.json)?

Maybe you have some average or other calculation in you query?

Query in my Grafana Installation:
`SELECT mean("download_mbs") FROM "speedtest" WHERE ("host" = 'YOUR_HOST_SEARCH') AND $timeFilter GROUP BY time($__interval) fill(null)`
