### ISSUE TITLE
Feature: Avoid zero values to influxdb

### ISSUE THREAD

**Issue by phoffi** [QuadStingray/docker-speedtest-influxdb#11]
Hi, 
sometimes there are zero-values in measurement, like:

![image](https://user-images.githubusercontent.com/43554440/107650775-1c842200-6c7f-11eb-98ae-6f9cd16ff2bc.png)

please add an option to repeat on zero or do not write to influxdb when one of the results is 0.

Thank you

**Comment by QuadStingray** [comment]
Option for Retry added in Version 1.1.0
