### ISSUE TITLE
Not available on docker hub?

### ISSUE THREAD

**Issue by dwilliss** [QuadStingray/docker-speedtest-influxdb#12]
I'm trying to get this using the docker pull command from the README, but it tells me 

> access denied for speedtest-influxdb, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

I tried doing a `docker login`, but that didn't help.

**Comment by dwilliss** [comment]
Figured it out.  For anybody who's not you, the command needs to be

`docker pull quadstingray/speedtest-influxdb`

**Comment by QuadStingray** [comment]
Thanks, I have updated the readme with the right command.
