### ISSUE TITLE
Container stops after a failed speedtest

### ISSUE THREAD

**Issue by jostrasser** [QuadStingray/docker-speedtest-influxdb#2]
Hi,

the container stops if one Speedtest fails or when Ookla do a server list maintenance and the url of the list is temporarily unavailable.

Is there a way to prevent this?

Thanks!

![Capture 2019-05-29 um 07 38 30](https://user-images.githubusercontent.com/14274103/58532204-10bfa600-81e5-11e9-815c-6e532d79fa4a.png)

**Comment by QuadStingray** [comment]
fixed with v. 0.9.3
