### ISSUE TITLE
Unknown unit type for distance

### ISSUE THREAD

**Issue by lhaley2011** [QuadStingray/docker-speedtest-influxdb#6]
I am trying to track down the unit type for the distance in influxdb. I can see you have an interface for [SpeedTestStatistics](https://github.com/QuadStingray/docker-speedtest-influxdb/blob/328f57caec7ddc50c6f607030404a2dd3b87499e/model/model.go#L33) and you are using it in the [influxdb file](https://github.com/QuadStingray/docker-speedtest-influxdb/blob/328f57caec7ddc50c6f607030404a2dd3b87499e/model/influxdb.go#L47).

What unit of measurement is http.Server.Distance?

**Comment by QuadStingray** [comment]
Hi,

sorry for late reply! The Distance was from Speedtest.net in KM. 
With the new Version 1.0.0 and my NDT7 Refactoring you can set you DistanceUnit with Docker Enviroment Variables, default is again KM.
