### ISSUE TITLE
Higher upload speed in speed test than real life

### ISSUE THREAD

**Issue by molnarti** [QuadStingray/docker-speedtest-influxdb#7]
I have a 60 Mbps uplink, and my usual speedtest values are matching this - speedtest-cli, speedtest.net, nperf.com, etc. but docker-speedtest-influxdb is consistently showing results like this:

`2020/06/19 07:40:49 Ping: 16.93 ms | Download: 92.52 Mbps | Upload: 81.37 Mbps,`

ping and download values are in line with the other measurements.

any idea why is this happening?

**Comment by QuadStingray** [comment]
Sorry, I have no idea. Maybe switch to new Version 1.0.0 with NDT7 Client will help?

**Comment by dwilliss** [comment]
I find that the NDT servers return higher than normal upload speeds too.  It sometimes tells me my upload speed is about 2x my download speed, which I know isn't true.  But that's not docker-speedtest-influxdb's fault.
